set(Plugin-SymbolicName "ctk.zoocmd.ui")
set(Plugin-ActivationPolicy "eager")
set(Plugin-Category "plugins")
set(Plugin-ContactAddress "https://github.com/shamozhishu")
set(Plugin-Description "A plugin for zooCmdUI")
set(Plugin-Name "ctk_zoocmd_ui")
set(Plugin-Vendor "shamozhishu")
set(Plugin-Version "1.0.0")