set(Plugin-SymbolicName "ctk.war.ui")
set(Plugin-ActivationPolicy "eager")
set(Plugin-Category "plugins")
set(Plugin-ContactAddress "https://github.com/shamozhishu")
set(Plugin-Description "A plugin for war ui")
set(Plugin-Name "ctk_war_ui")
set(Plugin-Vendor "shamozhishu")
set(Plugin-Version "1.0.0")
set(Require-Plugin "ctk.war")